version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "Carol@262457"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"  # Mudou aqui: 1434 no host, 1433 no container
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organizadorrotina-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrganizadorRotinaDB;User Id=sa;Password=Carol@262457;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    volumes:
      - .:/app

volumes:
  sql_data: